import "./globals.css";
import type { Metadata } from "next";
import AuthProvider from "./auth/Provider";
import Navbar from "@/components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg">
      <body className="bg-zinc-50">
        <AuthProvider>
          <main>
            <Navbar />
            <section className="container mx-auto mt-4">{children}</section>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
